server:
  port: "@server.port@"
spring:
  datasource:
    driver-class-name: "@datasource.classname@"
    username: "@datasource.username@"
    password: "@datasource.password@"
    url: "@datasource.url@"
    hikari:
      connectionTestQuery: SELECT 1 FROM DUAL
      # 连接池最大连接数
      maximum-pool-size: 10
      # 空闲时保持最小连接数
      minimum-idle: 5
      # 空闲连接存活时间
      idle-timeout: 300000
      # 连接超时时间
      connection-timeout: 20000
