server:
  port: @server.port@
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123
    url: jdbc:mysql://localhost:3306/foundation?serverTimezone=GMT
    hikari:
      connectionTestQuery: SELECT 1 FROM DUAL
      # 连接池最大连接数
      maximum-pool-size: 10
      # 空闲时保持最小连接数
      minimum-idle: 5
      # 空闲连接存活时间
      idle-timeout: 300000
      # 连接超时时间
      connection-timeout: 20000
